name: Elixir CI/CD

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  MIX_ENV: test
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.14.3" # Define the elixir version [required]
          otp-version: "25.2.1" # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Setup mix dependencies
        run: mix deps.get
      - name: Run lint check
        run: mix format --check-formatted
      - name: Run tests w/ coverage report
        run: mix test
